import { InstrumentType } from './wealth.schemas';

export const DEFAULT_INSTRUMENTS = [
  ['AAPL', 'Apple Inc.', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['MSFT', 'Microsoft Corporation', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['GOOGL', 'Alphabet Inc.', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['AMZN', 'Amazon.com Inc.', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['META', 'Meta Platforms Inc.', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['NVDA', 'NVIDIA Corporation', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['TSLA', 'Tesla Inc.', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['NFLX', 'Netflix Inc.', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['AMD', 'Advanced Micro Devices Inc.', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['INTC', 'Intel Corporation', InstrumentType.STOCK, 'USD', 'NASDAQ'],
  ['JPM', 'JPMorgan Chase & Co.', InstrumentType.STOCK, 'USD', 'NYSE'],
  ['V', 'Visa Inc.', InstrumentType.STOCK, 'USD', 'NYSE'],
  ['MA', 'Mastercard Inc.', InstrumentType.STOCK, 'USD', 'NYSE'],
  ['KO', 'The Coca-Cola Company', InstrumentType.STOCK, 'USD', 'NYSE'],
  ['WMT', 'Walmart Inc.', InstrumentType.STOCK, 'USD', 'NYSE'],
  ['DIS', 'The Walt Disney Company', InstrumentType.STOCK, 'USD', 'NYSE'],
  ['BABA', 'Alibaba Group Holding Ltd.', InstrumentType.STOCK, 'USD', 'NYSE'],
  ['SPY', 'SPDR S&P 500 ETF', InstrumentType.ETF, 'USD', 'NYSE'],
  ['QQQ', 'Invesco QQQ ETF', InstrumentType.ETF, 'USD', 'NASDAQ'],
  [
    'DIA',
    'SPDR Dow Jones Industrial Average ETF',
    InstrumentType.ETF,
    'USD',
    'NYSE',
  ],
  ['IWM', 'iShares Russell 2000 ETF', InstrumentType.ETF, 'USD', 'NYSE'],
  ['VOO', 'Vanguard S&P 500 ETF', InstrumentType.ETF, 'USD', 'NYSE'],
  ['VTI', 'Vanguard Total Stock Market ETF', InstrumentType.ETF, 'USD', 'NYSE'],
  ['VT', 'Vanguard Total World Stock ETF', InstrumentType.ETF, 'USD', 'NYSE'],
  [
    'EEM',
    'iShares MSCI Emerging Markets ETF',
    InstrumentType.ETF,
    'USD',
    'NYSE',
  ],
  ['GLD', 'SPDR Gold Shares', InstrumentType.ETF, 'USD', 'NYSE'],
  ['SLV', 'iShares Silver Trust', InstrumentType.ETF, 'USD', 'NYSE'],
  [
    'TLT',
    'iShares 20+ Year Treasury Bond ETF',
    InstrumentType.ETF,
    'USD',
    'NASDAQ',
  ],
  ['IBIT', 'iShares Bitcoin Trust ETF', InstrumentType.ETF, 'USD', 'NASDAQ'],
  ['AAPL-CEDEAR', 'CEDEAR Apple', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['MSFT-CEDEAR', 'CEDEAR Microsoft', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['GOOGL-CEDEAR', 'CEDEAR Alphabet', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['AMZN-CEDEAR', 'CEDEAR Amazon', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  [
    'META-CEDEAR',
    'CEDEAR Meta Platforms',
    InstrumentType.CEDEAR,
    'ARS',
    'BYMA',
  ],
  ['NVDA-CEDEAR', 'CEDEAR NVIDIA', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['TSLA-CEDEAR', 'CEDEAR Tesla', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['KO-CEDEAR', 'CEDEAR Coca-Cola', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['JPM-CEDEAR', 'CEDEAR JPMorgan Chase', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['V-CEDEAR', 'CEDEAR Visa', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['WMT-CEDEAR', 'CEDEAR Walmart', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['DISN-CEDEAR', 'CEDEAR Walt Disney', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['MELI-CEDEAR', 'CEDEAR MercadoLibre', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['SPY-CEDEAR', 'CEDEAR SPY', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['QQQ-CEDEAR', 'CEDEAR QQQ', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  ['DIA-CEDEAR', 'CEDEAR Dow Jones ETF', InstrumentType.CEDEAR, 'ARS', 'BYMA'],
  [
    'EEM-CEDEAR',
    'CEDEAR Emerging Markets ETF',
    InstrumentType.CEDEAR,
    'ARS',
    'BYMA',
  ],
  ['GGAL', 'Grupo Financiero Galicia', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['YPFD', 'YPF S.A.', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['BBAR', 'Banco BBVA Argentina', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['BMA', 'Banco Macro', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['SUPV', 'Grupo Supervielle', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['PAMP', 'Pampa Energía', InstrumentType.STOCK, 'ARS', 'BYMA'],
  [
    'TGSU2',
    'Transportadora de Gas del Sur',
    InstrumentType.STOCK,
    'ARS',
    'BYMA',
  ],
  [
    'TGNO4',
    'Transportadora de Gas del Norte',
    InstrumentType.STOCK,
    'ARS',
    'BYMA',
  ],
  ['CEPU', 'Central Puerto', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['EDN', 'Edenor', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['TRAN', 'Transener', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['COME', 'Sociedad Comercial del Plata', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['CRES', 'Cresud', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['LOMA', 'Loma Negra', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['TXAR', 'Ternium Argentina', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['ALUA', 'Aluar', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['MIRG', 'Mirgor', InstrumentType.STOCK, 'ARS', 'BYMA'],
  ['AL30', 'Bono República Argentina AL30', InstrumentType.BOND, 'ARS', 'BYMA'],
  ['AL35', 'Bono República Argentina AL35', InstrumentType.BOND, 'ARS', 'BYMA'],
  ['AE38', 'Bono República Argentina AE38', InstrumentType.BOND, 'ARS', 'BYMA'],
  ['GD29', 'Bono Global GD29', InstrumentType.BOND, 'ARS', 'BYMA'],
  ['GD30', 'Bono Global GD30', InstrumentType.BOND, 'ARS', 'BYMA'],
  ['GD35', 'Bono Global GD35', InstrumentType.BOND, 'ARS', 'BYMA'],
  ['GD38', 'Bono Global GD38', InstrumentType.BOND, 'ARS', 'BYMA'],
  ['GD41', 'Bono Global GD41', InstrumentType.BOND, 'ARS', 'BYMA'],
  ['BOPREAL1A', 'Bopreal Serie 1A', InstrumentType.BOND, 'USD', 'BYMA'],
  ['GD30D', 'Bono Global GD30 especie D', InstrumentType.BOND, 'USD', 'BYMA'],
  ['BTC', 'Bitcoin', InstrumentType.CRYPTO, 'USD', 'CRYPTO'],
  ['ETH', 'Ethereum', InstrumentType.CRYPTO, 'USD', 'CRYPTO'],
] as const;
