export type PaymentMethodInstitutionType = 'bank' | 'wallet';

export interface PaymentMethodInstitution {
  code: string;
  displayName: string;
  legalName?: string;
  bcraCode?: string;
  type: PaymentMethodInstitutionType;
  countryCode: 'AR';
  sortOrder: number;
  isActive: boolean;
}

export const PAYMENT_METHOD_INSTITUTIONS: readonly PaymentMethodInstitution[] =
  [
    {
      code: 'galicia',
      displayName: 'Banco Galicia',
      legalName: 'Banco de Galicia y Buenos Aires S.A.',
      bcraCode: '7',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 10,
      isActive: true,
    },
    {
      code: 'nacion',
      displayName: 'Banco Nación',
      legalName: 'Banco de la Nación Argentina',
      bcraCode: '11',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 20,
      isActive: true,
    },
    {
      code: 'provincia',
      displayName: 'Banco Provincia',
      legalName: 'Banco de la Provincia de Buenos Aires',
      bcraCode: '14',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 30,
      isActive: true,
    },
    {
      code: 'macro',
      displayName: 'Banco Macro',
      legalName: 'Banco Macro S.A.',
      bcraCode: '285',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 40,
      isActive: true,
    },
    {
      code: 'bbva',
      displayName: 'BBVA',
      legalName: 'Banco BBVA Argentina S.A.',
      bcraCode: '17',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 50,
      isActive: true,
    },
    {
      code: 'brubank',
      displayName: 'Brubank',
      legalName: 'Brubank S.A.U.',
      bcraCode: '143',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 60,
      isActive: true,
    },
    {
      code: 'icbc',
      displayName: 'ICBC',
      legalName: 'Industrial and Commercial Bank of China',
      bcraCode: '15',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 70,
      isActive: true,
    },
    {
      code: 'santander',
      displayName: 'Santander',
      legalName: 'Banco Santander Argentina S.A.',
      bcraCode: '72',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 80,
      isActive: true,
    },
    {
      code: 'supervielle',
      displayName: 'Supervielle',
      legalName: 'Banco Supervielle S.A.',
      bcraCode: '27',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 90,
      isActive: true,
    },
    {
      code: 'ciudad',
      displayName: 'Banco Ciudad',
      legalName: 'Banco de la Ciudad de Buenos Aires',
      bcraCode: '29',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 91,
      isActive: true,
    },
    {
      code: 'patagonia',
      displayName: 'Banco Patagonia',
      legalName: 'Banco Patagonia S.A.',
      bcraCode: '34',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 92,
      isActive: true,
    },
    {
      code: 'hipotecario',
      displayName: 'Banco Hipotecario',
      legalName: 'Banco Hipotecario S.A.',
      bcraCode: '44',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 93,
      isActive: true,
    },
    {
      code: 'credicoop',
      displayName: 'Banco Credicoop',
      legalName: 'Banco Credicoop Cooperativo Limitado',
      bcraCode: '191',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 94,
      isActive: true,
    },
    {
      code: 'comafi',
      displayName: 'Banco Comafi',
      legalName: 'Banco Comafi Sociedad Anónima',
      bcraCode: '299',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 95,
      isActive: true,
    },
    {
      code: 'banco-del-sol',
      displayName: 'Banco del Sol',
      legalName: 'Banco del Sol S.A.',
      bcraCode: '310',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 96,
      isActive: true,
    },
    {
      code: 'reba',
      displayName: 'Reba',
      legalName: 'Reba Compañía Financiera S.A.',
      bcraCode: '45072',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 97,
      isActive: true,
    },
    {
      code: 'bancor',
      displayName: 'Bancor',
      legalName: 'Banco de la Provincia de Córdoba S.A.',
      bcraCode: '20',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 98,
      isActive: true,
    },
    {
      code: 'banco-santa-fe',
      displayName: 'Banco Santa Fe',
      legalName: 'Nuevo Banco de Santa Fe S.A.',
      bcraCode: '330',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 99,
      isActive: true,
    },
    {
      code: 'banco-entre-rios',
      displayName: 'Banco Entre Ríos',
      legalName: 'Nuevo Banco de Entre Ríos S.A.',
      bcraCode: '386',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 100,
      isActive: true,
    },
    {
      code: 'banco-chaco',
      displayName: 'Nuevo Banco del Chaco',
      legalName: 'Nuevo Banco del Chaco S.A.',
      bcraCode: '311',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 101,
      isActive: true,
    },
    {
      code: 'banco-corrientes',
      displayName: 'Banco de Corrientes',
      legalName: 'Banco de Corrientes S.A.',
      bcraCode: '94',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 102,
      isActive: true,
    },
    {
      code: 'banco-formosa',
      displayName: 'Banco Formosa',
      legalName: 'Banco de Formosa S.A.',
      bcraCode: '315',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 103,
      isActive: true,
    },
    {
      code: 'banco-la-pampa',
      displayName: 'Banco de La Pampa',
      legalName: 'Banco de La Pampa S.E.M.',
      bcraCode: '93',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 104,
      isActive: true,
    },
    {
      code: 'bpn',
      displayName: 'Banco Provincia del Neuquén',
      legalName: 'Banco Provincia del Neuquén S.A.',
      bcraCode: '97',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 105,
      isActive: true,
    },
    {
      code: 'banco-chubut',
      displayName: 'Banco del Chubut',
      legalName: 'Banco del Chubut S.A.',
      bcraCode: '83',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 106,
      isActive: true,
    },
    {
      code: 'banco-santa-cruz',
      displayName: 'Banco Santa Cruz',
      legalName: 'Banco de Santa Cruz S.A.',
      bcraCode: '86',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 107,
      isActive: true,
    },
    {
      code: 'banco-tierra-del-fuego',
      displayName: 'Banco de Tierra del Fuego',
      legalName: 'Banco Provincia de Tierra del Fuego',
      bcraCode: '268',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 108,
      isActive: true,
    },
    {
      code: 'banco-san-juan',
      displayName: 'Banco San Juan',
      legalName: 'Banco de San Juan S.A.',
      bcraCode: '45',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 109,
      isActive: true,
    },
    {
      code: 'banco-santiago-del-estero',
      displayName: 'Banco Santiago del Estero',
      legalName: 'Banco de Santiago del Estero S.A.',
      bcraCode: '321',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 109.1,
      isActive: true,
    },
    {
      code: 'banco-rioja',
      displayName: 'Banco Rioja',
      legalName: 'Banco Rioja S.A.U.',
      bcraCode: '309',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 109.2,
      isActive: true,
    },
    {
      code: 'banco-columbia',
      displayName: 'Banco Columbia',
      legalName: 'Banco Columbia S.A.',
      bcraCode: '389',
      type: 'bank',
      countryCode: 'AR',
      sortOrder: 109.3,
      isActive: true,
    },
    {
      code: 'belo',
      displayName: 'Belo',
      type: 'wallet',
      countryCode: 'AR',
      sortOrder: 110,
      isActive: true,
    },
    {
      code: 'lemon',
      displayName: 'Lemon',
      type: 'wallet',
      countryCode: 'AR',
      sortOrder: 120,
      isActive: true,
    },
    {
      code: 'mercado-pago',
      displayName: 'Mercado Pago',
      legalName: 'MercadoLibre S.R.L.',
      bcraCode: '36502',
      type: 'wallet',
      countryCode: 'AR',
      sortOrder: 130,
      isActive: true,
    },
    {
      code: 'naranja-x',
      displayName: 'Naranja X',
      type: 'wallet',
      countryCode: 'AR',
      sortOrder: 140,
      isActive: true,
    },
    {
      code: 'personal-pay',
      displayName: 'Personal Pay',
      type: 'wallet',
      countryCode: 'AR',
      sortOrder: 150,
      isActive: true,
    },
    {
      code: 'prex',
      displayName: 'Prex',
      type: 'wallet',
      countryCode: 'AR',
      sortOrder: 160,
      isActive: true,
    },
    {
      code: 'uala',
      displayName: 'Ualá',
      type: 'wallet',
      countryCode: 'AR',
      sortOrder: 170,
      isActive: true,
    },
  ];

export const PAYMENT_METHOD_INSTITUTION_CODES = PAYMENT_METHOD_INSTITUTIONS.map(
  ({ code }) => code,
);

export function findPaymentMethodInstitution(
  code: string,
): PaymentMethodInstitution | undefined {
  return PAYMENT_METHOD_INSTITUTIONS.find(
    (institution) => institution.code === code && institution.isActive,
  );
}
